# Site settings
title: Elemeno
email: info@elemeno.cc
description: > # this means to ignore newlines until "baseurl:"
  Made with ♥ in Toronto
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://elemeno.cc" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
